"""
Sector taxonomy, per-sector KPIs, anonymous personas, challenge themes,
and indicative Amplitude outcomes used to personalise story arcs.
"""

SECTORS: dict = {
    "ecommerce": {
        "label": "E-commerce / Retail",
        "kpis": [
            "conversion rate",
            "cart abandonment rate",
            "average order value",
            "customer lifetime value",
            "repeat purchase rate",
            "checkout completion rate",
            "product page engagement",
            "ROAS",
            "retention rate",
            "net promoter score",
        ],
        "personas": [
            "a top-10 UK online retailer",
            "a fast-growing DTC brand",
            "a leading European marketplace",
            "a mid-market US e-commerce company",
            "a high-growth fashion retailer",
        ],
        "challenge_themes": [
            "data siloed across marketing, product, and CRM with no single funnel view",
            "analytics cycles too slow — insights arrived weeks after the moment to act",
            "no visibility into which product features drove repeat purchases",
            "A/B testing required engineering sprints, slowing experimentation to a crawl",
            "drop-off points in checkout were invisible until post-hoc quarterly reviews",
        ],
        "indicative_outcomes": {
            "conversion rate": "15–25% improvement in conversion rates within 90 days",
            "cart abandonment rate": "20–30% reduction in cart abandonment after funnel optimisation",
            "average order value": "10–20% increase in AOV through personalisation experiments",
            "customer lifetime value": "25–40% improvement in LTV through retention experiments",
            "repeat purchase rate": "15–30% improvement in repeat purchase rate",
            "checkout completion rate": "20–35% checkout completion uplift",
            "retention rate": "15–25% improvement in 90-day retention",
            "default": "15–25% improvement in key conversion and retention metrics within a quarter",
        },
    },
    "fintech": {
        "label": "Fintech / Financial Services",
        "kpis": [
            "onboarding completion rate",
            "KYC drop-off rate",
            "activation rate",
            "feature adoption",
            "daily active users",
            "transaction frequency",
            "churn rate",
            "NPS",
            "time to first transaction",
            "support ticket volume",
        ],
        "personas": [
            "a Series B European fintech",
            "a leading UK challenger bank",
            "a high-growth payments startup",
            "a licensed investment platform",
            "a mid-market lending platform",
        ],
        "challenge_themes": [
            "high drop-off during regulated onboarding flows with no way to diagnose why",
            "unable to understand which features actually drove user activation",
            "compliance constraints made traditional analytics tools difficult to deploy",
            "no real-time view of where users stalled inside the product",
            "fragmented data across web, mobile, and back-office systems",
        ],
        "indicative_outcomes": {
            "onboarding completion rate": "30–45% improvement in onboarding completion",
            "KYC drop-off rate": "25–40% reduction in KYC drop-off through friction removal",
            "activation rate": "20–35% improvement in activation within first 7 days",
            "feature adoption": "25–40% increase in feature adoption",
            "churn rate": "15–25% reduction in churn through early warning signals",
            "time to first transaction": "40% faster time to first transaction",
            "default": "25–40% improvement in activation and onboarding completion",
        },
    },
    "media_entertainment": {
        "label": "Media / Entertainment",
        "kpis": [
            "daily active users",
            "monthly active users",
            "DAU/MAU ratio",
            "content engagement rate",
            "average session length",
            "subscriber retention",
            "content completion rate",
            "paid conversion rate",
            "churn rate",
            "recommendation click-through rate",
        ],
        "personas": [
            "a leading streaming platform",
            "a top-10 digital publisher",
            "a fast-growing podcast network",
            "a major sports media brand",
            "a subscription news platform",
        ],
        "challenge_themes": [
            "content recommendation wasn't personalised — one algorithm served everyone",
            "couldn't understand why subscribers cancelled until it was too late to intervene",
            "no visibility into which content types drove long-term subscriber retention",
            "A/B testing the recommendation engine required months of data science time",
            "editorial and product teams worked with entirely different datasets",
        ],
        "indicative_outcomes": {
            "daily active users": "20–35% improvement in DAU through personalisation",
            "content engagement rate": "25–40% increase in content engagement",
            "subscriber retention": "15–25% improvement in subscriber retention",
            "churn rate": "20–30% reduction in subscriber churn",
            "paid conversion rate": "15–25% improvement in free-to-paid conversion",
            "DAU/MAU ratio": "10–20 point improvement in DAU/MAU stickiness ratio",
            "default": "20–35% improvement in engagement and subscriber retention",
        },
    },
    "saas": {
        "label": "SaaS / Technology",
        "kpis": [
            "trial-to-paid conversion",
            "time to value",
            "feature adoption rate",
            "monthly active users",
            "churn rate",
            "net revenue retention",
            "expansion revenue",
            "product qualified leads",
            "onboarding completion",
            "support ticket deflection",
        ],
        "personas": [
            "a Series C B2B SaaS company",
            "a leading developer tools platform",
            "a fast-growing HR tech startup",
            "a mid-market CRM vendor",
            "a vertical SaaS company with 500+ enterprise customers",
        ],
        "challenge_themes": [
            "product and customer success had different, contradictory views of user behaviour",
            "couldn't identify which in-product actions correlated with expansion or churn",
            "every experiment required a 4-week engineering sprint to instrument and run",
            "no signal on which onboarding steps caused trial users to abandon",
            "churn was identified retrospectively from cancelled contracts, never proactively",
        ],
        "indicative_outcomes": {
            "trial-to-paid conversion": "20–35% improvement in trial-to-paid conversion",
            "time to value": "40–60% reduction in time to first value moment",
            "feature adoption rate": "30–50% increase in feature adoption",
            "churn rate": "15–30% reduction in churn through early warning signals",
            "net revenue retention": "5–15 point improvement in NRR through expansion signals",
            "onboarding completion": "30–50% improvement in onboarding completion rates",
            "default": "30–50% improvement in activation and feature adoption",
        },
    },
    "gaming": {
        "label": "Gaming",
        "kpis": [
            "D1 / D7 / D30 retention",
            "ARPDAU",
            "ARPPU",
            "average session length",
            "level completion rate",
            "IAP conversion rate",
            "live ops engagement",
            "churn rate",
            "virality coefficient",
            "lifetime value",
        ],
        "personas": [
            "a top-20 mobile games studio",
            "a fast-growing casual games publisher",
            "a leading mid-core games developer",
            "an independent RPG studio",
            "a hypercasual games company",
        ],
        "challenge_themes": [
            "live ops decisions were based on aggregate cohort data, not granular player segments",
            "A/B testing new levels took weeks due to slow data pipeline processing",
            "couldn't correlate early player actions with long-term LTV until it was too late",
            "monetisation experiments had no statistical rigour — teams were guessing",
            "player drop-off points were invisible until post-launch retrospective analysis",
        ],
        "indicative_outcomes": {
            "D1 / D7 / D30 retention": "20–35% improvement in D1/D7/D30 retention",
            "ARPDAU": "15–25% improvement in ARPDAU through monetisation experiments",
            "IAP conversion rate": "20–40% improvement in IAP conversion",
            "level completion rate": "25–35% improvement through difficulty curve optimisation",
            "default": "20–35% improvement in retention and monetisation metrics",
        },
    },
    "travel": {
        "label": "Travel / Hospitality",
        "kpis": [
            "booking conversion rate",
            "search-to-book rate",
            "repeat booking rate",
            "average booking value",
            "cancellation rate",
            "loyalty programme engagement",
            "mobile app adoption",
            "NPS",
            "ancillary revenue per booking",
        ],
        "personas": [
            "a leading European OTA",
            "a top-10 global hotel chain",
            "a fast-growing travel startup",
            "a major airline's digital team",
            "a mid-market cruise line",
        ],
        "challenge_themes": [
            "no visibility into the micro-moments that determined booking intent vs. abandonment",
            "personalisation was limited to basic geo-targeting with no behavioural signal",
            "couldn't understand why high-intent users abandoned the booking flow on mobile",
            "data was siloed between web, app, and CRM with no unified customer view",
            "experiments took 6+ weeks to design, instrument, run, and read out",
        ],
        "indicative_outcomes": {
            "booking conversion rate": "15–25% improvement in booking conversion",
            "search-to-book rate": "20–30% improvement in search-to-book conversion",
            "repeat booking rate": "20–35% improvement in repeat bookings",
            "cancellation rate": "15–25% reduction in cancellation rates",
            "default": "15–25% improvement in conversion and repeat booking metrics",
        },
    },
    "healthcare": {
        "label": "Healthcare / Health Tech",
        "kpis": [
            "patient activation rate",
            "app daily active users",
            "appointment booking rate",
            "medication adherence",
            "care plan completion",
            "programme dropout rate",
            "time to first care action",
            "NPS",
            "feature adoption",
        ],
        "personas": [
            "a leading digital health platform",
            "a regulated telehealth provider",
            "a fast-growing mental wellness app",
            "a mid-market occupational health company",
            "a consumer health monitoring startup",
        ],
        "challenge_themes": [
            "understanding what drove patient adherence required months of manual analysis",
            "no real-time signal on which features actually increased care plan completion",
            "HIPAA constraints made traditional analytics tools difficult or impossible to use",
            "product iterations were based on NPS surveys, not actual patient behaviour",
            "couldn't identify which onboarding steps correlated with long-term engagement",
        ],
        "indicative_outcomes": {
            "patient activation rate": "25–40% improvement in patient activation",
            "appointment booking rate": "20–35% improvement in booking completion",
            "programme dropout rate": "20–30% reduction in programme dropout",
            "care plan completion": "25–40% improvement in care plan completion rates",
            "default": "25–40% improvement in patient activation and programme completion",
        },
    },
}

COMPANY_SIZES = ["startup", "mid-market", "enterprise"]
REGIONS = ["NA", "EMEA", "APAC", "LATAM", "Global"]
